# RPM spec for ollamux — built in CI (fedora container) and via COPR.
# Vendored sources: Source1 is generated by scripts/vendor-source.sh
# from Cargo.lock at release time; %prep below wires the offline build.
Name:           ollamux
Version:        0.4.0
Release:        1%{?dist}
Summary:        Key-rotating reverse proxy for the Ollama Cloud API

License:        GPL-2.0-or-later
URL:            https://github.com/j-stechmann/ollamux
Source0:        %{url}/archive/v%{version}/ollamux-%{version}.tar.gz
Source1:        ollamux-%{version}-vendor.tar.xz
Source2:        ollamux.service
Source3:        ollamux.1

BuildRequires:  cargo
BuildRequires:  gcc
BuildRequires:  rustc >= 1.85
BuildRequires:  systemd-rpm-macros
Requires:       systemd
%{?systemd_requires}

%global _description %{expand:
ollamux gives several Ollama Cloud API keys and serves them combined behind
one local endpoint. Requests are spread across keys (round-robin,
least-loaded first), and when a key is rate-limited, rejected, or
invalid, the request silently retries on the next key before anything
reaches the client. Not a local Ollama server: it proxies to
https://ollama.com.}

%description %{_description}

%prep
%autosetup -p1 -n ollamux-%{version}
# vendor/ from the vendor tarball lands inside the source tree; cargo_prep
# then wires crates.io -> ./vendor (offline).
tar -xJf %{SOURCE1}
%cargo_prep -v vendor

%build
export RUSTFLAGS="%{build_rustflags}"
%cargo_build

%install
export RUSTFLAGS="%{build_rustflags}"
%cargo_install
install -Dm0644 %{SOURCE2} %{buildroot}%{_unitdir}/ollamux.service
install -Dm0644 %{SOURCE3} %{buildroot}%{_mandir}/man1/ollamux.1
# cargo_install registers the crate in /usr/share/cargo/registry; an
# application package owns only the binary, unit and man page.
rm -rf %{buildroot}/usr/share/cargo/registry

%check
%cargo_test

%files
%license LICENSE
%doc README.md
%{_bindir}/ollamux
%{_unitdir}/ollamux.service
%{_mandir}/man1/ollamux.1*

%post
%systemd_post ollamux.service

%preun
%systemd_preun ollamux.service

%postun
%systemd_postun ollamux.service

%changelog
* Tue Sep 01 2026 Jonathan Stechmann <69059260+j-stechmann@users.noreply.github.com> - 0.4.0-1
- Usage introspection (/_usage) and quota-aware key routing
  (--usage-aware); /_keys embeds per-key usage.

* Sun Aug 30 2026 Jonathan Stechmann <69059260+j-stechmann@users.noreply.github.com> - 0.3.0-1
- Silent logging by default (-v for verbose); agent-friendly errors,
  X-Ollamux identity header.

* Sun Aug 30 2026 Jonathan Stechmann <69059260+j-stechmann@users.noreply.github.com> - 0.2.0-1
- Rebrand: omlx is now ollamux (Ollama multiplexer); renamed env vars,
  headers, error codes and config paths.

* Sun Aug 30 2026 Jonathan Stechmann <69059260+j-stechmann@users.noreply.github.com> - 0.1.0-1
- Initial package