# RPM spec for omlx — built in CI (fedora container) and via COPR.
# Vendored sources: Source1 is generated by scripts/vendor-source.sh
# from Cargo.lock at release time; %prep below wires the offline build.
Name:           omlx
Version:        0.1.0
Release:        1%{?dist}
Summary:        Key-rotating reverse proxy for the Ollama Cloud API

License:        GPL-2.0-or-later
URL:            https://github.com/j-stechmann/omlx
Source0:        %{url}/archive/v%{version}/omlx-%{version}.tar.gz
Source1:        omlx-%{version}-vendor.tar.xz
Source2:        omlx.service
Source3:        omlx.1

BuildRequires:  cargo
BuildRequires:  gcc
BuildRequires:  rustc >= 1.85
BuildRequires:  systemd-rpm-macros
Requires:       systemd
%{?systemd_requires}

%global _description %{expand:
omlx gives several Ollama Cloud API keys and serves them combined behind
one local endpoint. Requests are spread across keys (round-robin,
least-loaded first), and when a key is rate-limited, rejected, or
invalid, the request silently retries on the next key before anything
reaches the client. Not a local Ollama server: it proxies to
https://ollama.com.}

%description %{_description}

%prep
%autosetup -p1 -n omlx-%{version}
# vendor/ from the vendor tarball lands inside the source tree; cargo_prep
# then wires crates.io -> ./vendor (offline).
tar -xJf %{SOURCE1}
%cargo_prep -v vendor

%build
export RUSTFLAGS="%{build_rustflags}"
%cargo_build

%install
export RUSTFLAGS="%{build_rustflags}"
%cargo_install
install -Dm0644 %{SOURCE2} %{buildroot}%{_unitdir}/omlx.service
install -Dm0644 %{SOURCE3} %{buildroot}%{_mandir}/man1/omlx.1

%check
%cargo_test

%files
%license LICENSE
%doc README.md
%{_bindir}/omlx
%{_unitdir}/omlx.service
%{_mandir}/man1/omlx.1*

%post
%systemd_post omlx.service

%preun
%systemd_preun omlx.service

%postun
%systemd_postun omlx.service

%changelog
* Sun Aug 30 2026 Jonathan Stechmann <69059260+j-stechmann@users.noreply.github.com> - 0.1.0-1
- Initial package